name:                cider
version:             0.2.0.0
github:              "mdippery/cider"
license:             LGPL-3
author:              "Michael Dippery"
maintainer:          "michael@monkey-robot.com"
copyright:           "2019 Michael Dippery"

extra-source-files:
  - COPYING

synopsis:            Calculates IP addresses contained in a CIDR block
category:            Networking

description: |
  Calculates IP addresses contained in a CIDR block.
  .
  This package contains both a command-line utility called @cider@
  and a module for working with IP addresses.

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-type-defaults
  dependencies:
    - split

executables:
  cider:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - cider

tests:
  cider-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cider
      - hspec
