name:                pyxis
version:             0.1.0.0
github:              "mdippery/pyxis"
license:             GPL-3
author:              "Michael Dippery"
maintainer:          "michael@monkey-robot.com"
copyright:           "2019 Michael Dippery"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdippery/pyxis#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  pyxis:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - saturn
