name:                cider
version:             0.2.0.0
github:              "mdippery/cider"
license:             LGPL-3
author:              "Michael Dippery"
maintainer:          "michael@monkey-robot.com"
copyright:           "2019 Michael Dippery"

extra-source-files:
  - COPYING

synopsis:            Calculates IP addresses contained in a CIDR block
category:            Networking

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdippery/cider#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-type-defaults
  dependencies:
    - split

executables:
  cider:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - cider

tests:
  cider-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cider
      - hspec
