name:                pyxis
version:             0.1.0.0
github:              "mdippery/pyxis"
license:             BSD3
author:              "Michael Dippery"
maintainer:          "michael@monkey-robot.com"
copyright:           "2019 Michael Dippery"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdippery/pyxis#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pyxis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pyxis

tests:
  pyxis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pyxis
